development:
  adapter: postgresql
  database: testapi_development
  encoding: utf8
  username: loganmcansh
  password:
  host: localhost

production:
  adapter: postgresql
  database: testapi_production
  encoding: utf8
  username: loganmcansh
  password:
  host: localhost

test:
  adapter: postgresql
  database: testapi_test
  encoding: utf8
  username: loganmcansh
  password:
  host: localhost
